# Generated by Django 5.1.4 on 2024-12-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_usersubmission_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
